### ISSUE TITLE
About unable to display network drives

### ISSUE THREAD

**Issue by ellenchua** [zhuxb711/RX-Explorer#121] opened 2021-02-17 08:06 UTC
In Rx, you can only display the local drive letter, but not the network drive letter. How can I add it?

**Comment by chengl404** [comment] 2021-02-19 06:35
Duplicate of #97 
fix in next.

**Comment by zhuxb711** [comment] 2021-02-23 03:41
Might be fixed in 6.1.0, support for network drive is in beta. It might not work.~~~~

**Closed** 2021-02-23 16:26 UTC
Labels: Bug, Pending release
